### ISSUE TITLE
Cherry pick lodash

### ISSUE THREAD

**Issue by thangngoc89** [mikenikles/html-to-react#22]
This would help decrease bundle size of website that use this package.

I can send a PR to cherry pick lodash directly in `html-to-react`
Or setup a babel build step to do it automatically via [babel-plugin-lodash@1.1.0](https://github.com/lodash/babel-plugin-lodash/tree/v1.1.0) (last version that compitable with lodash 3.10.x)

**Comment by no23reason** [comment]
This is solved in #25 (although not automatically).

**Comment by mikenikles** [comment]
@thangngoc89 I just merged #25 which cherry picks lodash dependencies. I'm going to close this issue, but feel free to re-open if you feel there's more we can do. I'm happy to discuss that.
