### ISSUE TITLE
using import instead of require

### ISSUE THREAD

**Issue by msimonc** [mikenikles/html-to-react#26]
When I do:

import HtmlToReact from 'html-to-react';

or
import { HtmlToReact } from 'html-to-react';

I get:

./~/html-to-react/~/htmlparser2/~/entities/maps/entities.json
Module parse failed: ... /node_modules/entities/maps/entities.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.

Thanks

**Comment by geecu** [comment]
You need to install and configure json-loader:
`npm install json-loader`
then in webpack.config.js:
`      
  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json'
      },
      ...
    ]
  }
`
