### ISSUE TITLE
Img, br and hr tags produce warnings

### ISSUE THREAD

**Issue by RacingTadpole** [mikenikles/html-to-react#29]
Eg. This test fails with an error:

        it('should return a valid HTML with img', function() {
            var htmlInput = '<div><img src="www.example.com"/></div>';

            var reactComponent = parser.parse(htmlInput);
            var reactHtml = ReactDOMServer.renderToStaticMarkup(reactComponent);

            assert.equal(reactHtml, htmlInput);
        });

```Warning: img is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`.```

**Comment by mikenikles** [comment]
Fixed in #17
