### ISSUE TITLE
Html->React attributes

### ISSUE THREAD

**Issue by v3yr0n** [mikenikles/html-to-react#35]
Hey!
To fix some react warnings can you add this to the next release, in the process-node-definitions.js?

`if (node.attribs) {
            forEach(node.attribs, function(value, key) {
                switch (key || '') {
                    case 'style':
                        elementProps.style = createStyleJsonFromString(node.attribs.style);
                        break;
                    case 'class':
                        elementProps.className = value;
                        break;
                     case 'maxlength':
                        elementProps.maxLength = value;
                        break;
                     case 'for':
                        elementProps.htmlFor = value;
                        break;
                     case 'itemprop':
                        elementProps.itemProp = value;
                        break;
                    default:
                        elementProps[key] = value;
                        break;
                }
            });
        }`

Thanks!

**Comment by no23reason** [comment]
@v3yr0n, why not make a pull request with it? ;)

**Comment by v3yr0n** [comment]
I made one but it was not accepted yet :)

**Comment by no23reason** [comment]
Oh, my bad :) next time, please reference it, so it is clearer.
Related PR: #36
