### ISSUE TITLE
Use with React 15

### ISSUE THREAD

**Issue by Slapbox** [mikenikles/html-to-react#42]
Not sure what version of React this was written for, but for React 15 you need to import ReactDOMServer.

```
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import * as HtmlToReact from 'html-to-react';

const htmlInput = '<div><h1>Title</h1><p>A paragraph</p></div>';
const htmlToReactParser = new HtmlToReact.Parser(React);
const reactComponent = htmlToReactParser.parse(htmlInput);
const reactHtml = ReactDOMServer.renderToStaticMarkup(reactComponent);

```

Unfortunately it just outputs a string of identical to the HTML input though for me.

**Comment by aknuds1** [comment]
You could try [my version](https://github.com/aknuds1/html-to-react) and see if it works better for you.

**Comment by aknuds1** [comment]
This is solved now in master.
