### ISSUE TITLE
🎉 Announcement: Looking for a maintainer 🎉

### ISSUE THREAD

**Issue by mikenikles** [mikenikles/html-to-react#43]
Hey!

Based on what I see on the NPM website, there are quite a few users of `html-to-react`:

![image](https://cloud.githubusercontent.com/assets/788827/18389994/43dfb6d8-765d-11e6-9b26-116c83d2514d.png)

Is anyone interested in taking over the maintenance for this package? I have taken on some new responsibilities that keep me busy.

Please let me know.

Thanks,

Mike

**Comment by aknuds1** [comment]
I can take over maintenance.

**Comment by mikenikles** [comment]
Awesome, thanks @aknuds1! I've made you a collaborator. Happy to discuss any questions you may have.

**Comment by mikenikles** [comment]
To close the loop, `html-to-react` now lives at https://github.com/aknuds1/html-to-react. Thanks @aknuds1 for all your help so far and for taking over the project.
