### ISSUE TITLE
Missing test-locally

### ISSUE THREAD

**Issue by RacingTadpole** [mikenikles/html-to-react#44]
In the README you mention using `npm run test-locally` to run the tests. However this task has disappeared in `package.json`. It would be easy to add back with:

```
  "scripts": {
    ...
    "test-locally": "./node_modules/mocha/bin/mocha",
    ...
```

Or to change the README.

**Comment by aknuds1** [comment]
I've changed it so that `npm run test` works for testing locally, without coverage.
