### ISSUE TITLE
best way to pass callbacks?

### ISSUE THREAD

**Issue by adamwong246** [mikenikles/html-to-react#5]
I am implementing an html editor with contentEditable and this means parsing html into a react component. However, given the arbitrary depth of the tree, I've found the best way to propagate changes is via callbacks passed through props- when a element is updated, it calls back to it's parent with an updated result. The parent does the same and so on, all the way back to the top.

Identifying the root node is easy
```
  {
    shouldProcessNode: (node) ->
      node.parent?.parent == null
    processNode: (node, children) ->
     React.createElement(node.name, {theCallback: theFinalCallback}, children)
  }
````

but I'm unsure how to pass props to each child
```
  {
    shouldProcessNode: (node) ->
      node.parent?.parent != null
    processNode: (node, children) ->
     React.createElement(node.name, {theCallback: node.parent.props.theCallback}, children)
  }
```

Obviously, this won't work, as ```node``` is just an object, not a react component. ideas?

**Comment by aindlq** [comment]
Html is parsed bottom up. So parent react element is created only when all children are ready.
Do you really need to propagate changes through whole hierarchy? 
From the first look this is the perfect use-case for one directional data.

**Comment by adamwong246** [comment]
Since it's bottom up, this package won't work for my aims.

But yeah, I think it does need to render down and propagate changes up. My editor works like this- given an html string (the "model" as it were) it produces react-ified html in the DOM (the "view") which is decorated with some controls for editing text, adding and removing elements, editing attributes, etc. 

Now consider some element somewhere in that tree- do we really want every node to speak directly to the store? Because that's my understanding of unidirectional data. It would require that at every point in the tree that an edit can be made, there's a complex transform to make the corresponding change to the model. 

Instead, let each element just pass it's edit to the parent component, which integrates this change into it's branch, then repeat all the way to the top. Once at the top, unidirectionally set the changed html, and then re-render. So if you consider the tree as a component, data is unidirectional. Within the tree, however, communication is recursive callbacks. Communication in or out of the tree is only done through the root node and each view element is responsible for integrating changes into it's own branch of the model.
![diagram](https://cloud.githubusercontent.com/assets/474792/11325581/589e1aac-9106-11e5-89af-d86cefc26430.jpg)

**Comment by adamwong246** [comment]
Though if you see a better way to accomplish this, I am interested!
