### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method

### ISSUE THREAD

**Issue by mattdell** [mikenikles/html-to-react#7]
I'm getting this error on some HTML I've rendered. Does this library have support for keys?

**Comment by mikenikles** [comment]
Hey Matt,

Do you have sample code that outlines this error? I'd be happy to investigate this.

Cheers,

Mike

**Comment by mattdell** [comment]
Hi Mike,

This is the HTML causing the problem.

`<p>Send an <a href=\'#\'>email</a>, give us a call on <a href=\'#\'>00000 000000</a> or see our <a href=\'#\'>FAQs</a>.</p>`

Though I have a helper util that wraps everything in a div since the library requires a single parent so that resolves to

`<div><p>Send an <a href=\'#\'>email</a>, give us a call on <a href=\'#\'>00000 000000</a> or see our <a href=\'#\'>FAQs</a>.</p></div>`

Seems react doesn't like having sibling anchor tags and wants a key to be there. The Indicee version takes care of this but isn't available as an npm package.

**Comment by lithin** [comment]
+1 

I'm parsing a super simple html and I'm getting the same error:

`<div></p>First paragraph</p><p>Second paragraph</p></div>`

**Comment by mikenikles** [comment]
This has been fixed and is available in version 0.1.2.
